### ISSUE TITLE
Remove Spills Related Tables

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-eid-skid#18]
DEQ said that once we add a link to the Salesforce PDF, we could remove the related tables from the Environmental Incidents layer.

Related Tables:
- Chemicals: https://utahdeq.maps.arcgis.com/home/item.html?id=650cbe060f67471b93b8eee4318ddff7
- Impacted Media: https://utahdeq.maps.arcgis.com/home/item.html?id=5273dbb9871d482190ebda97ed0e0083

Blocked by: https://github.com/agrc/deq-enviro/issues/764

### Tasks

- [x] remove related tables from https://github.com/agrc/deq-eid-skid
- [x] remove related table configs from enviro config spreadsheets (prod & dev)
- [x] open porter deprecation issues for the two related tables
- [ ] delete corresponding AGOL items in DEQ's AGOL org
