### ISSUE TITLE
Update Spills ID Field

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-eid-skid#19]
Currently, the value for the "Spill ID" (`Id`) comes from the Salesforce field: `Id`. It contains values like this: `500eq000000W3h7AAC`.

This needs to be changed to the spill incident number in Salesforce.

New field name: `CaseNumber`

### Tasks

- [x] change the [skid config](https://github.com/agrc/deq-eid-skid/blob/main/src/deq_eid/config.py) to point to the new SF field name
- [x] add the old SF `Id` field as a new field named: `Salesforce_Id`. We'll need it to [link to the report PDF](https://github.com/agrc/deq-enviro/issues/764).
- [x] Add the new field to the [production incidents service](https://www.arcgis.com/home/item.html?id=635d1639bf6d4d398700405c8e40acfe)
